# Generated by Django 4.2.16 on 2024-10-22 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="property_management.lease",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="property",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="property_management.property",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="renter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="users.renter",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leases",
                to="property_management.property",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="renter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leases",
                to="users.renter",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leases",
                to="users.tenant",
            ),
        ),
    ]
