# Generated by Django 5.1.1 on 2024-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0003_remove_lease_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
