# Generated by Django 5.1.1 on 2024-11-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_management', '0003_blogpost_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog_post',
        ),
    ]
